name: On main workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: python -m pip install uv
      - name: Install dependencies
        run: uv sync

      - name: Lint
        run: make lint
      - name: Test
        run: make test
    #   - name: Coverage report
    #     run: |
    #       make webserver-coverage